# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntest.proto\"\x14\n\x03Req\x12\r\n\x05query\x18\x01 \x01(\t\"\x16\n\x04Resp\x12\x0e\n\x06result\x18\x01 \x01(\t2\x8d\x01\n\nRpcService\x12\x1a\n\tSimpleRpc\x12\x04.Req\x1a\x05.Resp\"\x00\x12\x1f\n\x0c\x63lientStream\x12\x04.Req\x1a\x05.Resp\"\x00(\x01\x12\x1f\n\x0cserverStream\x12\x04.Req\x1a\x05.Resp\"\x00\x30\x01\x12!\n\x0c\x64oubleStream\x12\x04.Req\x1a\x05.Resp\"\x00(\x01\x30\x01\x42\x0f\n\x0borg.exampleP\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'test_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013org.exampleP\000'
  _globals['_REQ']._serialized_start=14
  _globals['_REQ']._serialized_end=34
  _globals['_RESP']._serialized_start=36
  _globals['_RESP']._serialized_end=58
  _globals['_RPCSERVICE']._serialized_start=61
  _globals['_RPCSERVICE']._serialized_end=202
# @@protoc_insertion_point(module_scope)
