# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import test_pb2 as test__pb2

GRPC_GENERATED_VERSION = '1.64.1'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in test_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class RpcServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SimpleRpc = channel.unary_unary(
                '/RpcService/SimpleRpc',
                request_serializer=test__pb2.Req.SerializeToString,
                response_deserializer=test__pb2.Resp.FromString,
                _registered_method=True)
        self.clientStream = channel.stream_unary(
                '/RpcService/clientStream',
                request_serializer=test__pb2.Req.SerializeToString,
                response_deserializer=test__pb2.Resp.FromString,
                _registered_method=True)
        self.serverStream = channel.unary_stream(
                '/RpcService/serverStream',
                request_serializer=test__pb2.Req.SerializeToString,
                response_deserializer=test__pb2.Resp.FromString,
                _registered_method=True)
        self.doubleStream = channel.stream_stream(
                '/RpcService/doubleStream',
                request_serializer=test__pb2.Req.SerializeToString,
                response_deserializer=test__pb2.Resp.FromString,
                _registered_method=True)


class RpcServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SimpleRpc(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def clientStream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def serverStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def doubleStream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RpcServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SimpleRpc': grpc.unary_unary_rpc_method_handler(
                    servicer.SimpleRpc,
                    request_deserializer=test__pb2.Req.FromString,
                    response_serializer=test__pb2.Resp.SerializeToString,
            ),
            'clientStream': grpc.stream_unary_rpc_method_handler(
                    servicer.clientStream,
                    request_deserializer=test__pb2.Req.FromString,
                    response_serializer=test__pb2.Resp.SerializeToString,
            ),
            'serverStream': grpc.unary_stream_rpc_method_handler(
                    servicer.serverStream,
                    request_deserializer=test__pb2.Req.FromString,
                    response_serializer=test__pb2.Resp.SerializeToString,
            ),
            'doubleStream': grpc.stream_stream_rpc_method_handler(
                    servicer.doubleStream,
                    request_deserializer=test__pb2.Req.FromString,
                    response_serializer=test__pb2.Resp.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'RpcService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('RpcService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RpcService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SimpleRpc(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/RpcService/SimpleRpc',
            test__pb2.Req.SerializeToString,
            test__pb2.Resp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def clientStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/RpcService/clientStream',
            test__pb2.Req.SerializeToString,
            test__pb2.Resp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def serverStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/RpcService/serverStream',
            test__pb2.Req.SerializeToString,
            test__pb2.Resp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def doubleStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/RpcService/doubleStream',
            test__pb2.Req.SerializeToString,
            test__pb2.Resp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
